spring:
    datasource:
        url: jdbc:mysql://localhost:3306/university?useSSL=false
        username: "root"
        password: ""
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                show_sql: true
security:
  basic:
    enabled: false
